// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aplikasi_asep.Database.Context;

#nullable disable

namespace aplikasi_asep.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260904185016_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("aplikasi_asep.Models.Entities.PlanningDayRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalValue")
                        .HasColumnType("int");

                    b.Property<int>("PlanningRecordId")
                        .HasColumnType("int");

                    b.Property<int>("ResultValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlanningRecordId");

                    b.ToTable("PlanningDayRecords");
                });

            modelBuilder.Entity("aplikasi_asep.Models.Entities.PlanningRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PlanningRecords");
                });

            modelBuilder.Entity("aplikasi_asep.Models.Entities.PlanningDayRecord", b =>
                {
                    b.HasOne("aplikasi_asep.Models.Entities.PlanningRecord", "PlanningRecord")
                        .WithMany("DayRecords")
                        .HasForeignKey("PlanningRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanningRecord");
                });

            modelBuilder.Entity("aplikasi_asep.Models.Entities.PlanningRecord", b =>
                {
                    b.Navigation("DayRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
